trustbloc/fabric-mod

.github/stale.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: Reset stale github bot configuration

core/ledger/ledgerstorage/store.go, extensions/blkstorage/store.go, extensions/blkstorage/store_test.go, extensions/go.sum
=> [#18] Add hook to switch blkstorage impl

core/ledger/ledgerstorage/store.go, core/ledger/pvtdatastorage/store.go, extensions/go.sum, extensions/pvtdatastorage/store.go, extensions/pvtdatastorage/store_test.go
=> [#16] Add hook to switch pvtdatastorage impl

core/ledger/kvledger/idstore/idstore.go, core/ledger/kvledger/idstore/idstore_test.go, core/ledger/kvledger/idstore/test_exports.go, core/ledger/kvledger/kv_ledger_provider.go, core/ledger/kvledger/kv_ledger_provider_test.go, extensions/idstore/store.go, extensions/idstore/store_test.go
- Add idstore interface
- Add idstore hook in kevlar
=> [#20] Add hook to switch idstore impl

common/util/retry/retry.go, common/util/retry/retry_test.go, core/ledger/util/couchdb/couchdb_ext.go, core/ledger/util/couchdb/couchdb_ext_test.go, core/ledger/util/couchdb/couchdbutil_ext.go, core/ledger/util/couchdb/couchdbutil_ext_test.go
=> [#22] Add couchdb helper methods

scripts/run-unit-tests.sh
=> [#26] configure number of unit-test run in parallel

integration/e2e/e2e_signal_test.go, integration/nwo/core_template.go, integration/nwo/network.go
=> [#24] Add designated couchdb per peer for fabric integration tests

docs/requirements.txt
=> [#30] Upgrade Jinja to 2.10.1

peer/node/main.go, peer/node/main_test.go
=> [#37] Expose peer node startup as library

core/ledger/kvledger/txmgmt/rwsetutil/rwset_builder.go, core/ledger/kvledger/txmgmt/rwsetutil/rwset_proto_util.go, core/ledger/kvledger/txmgmt/rwsetutil/rwset_proto_util_test.go, extensions/gossip/coordinator/coordinator.go, extensions/gossip/coordinator/coordinator_test.go, gossip/privdata/coordinator.go, gossip/privdata/coordinator_test.go
Signed-off-by: Firas Qutishat firas.qutishat@securekey.com
Signed-off-by: Bob Stasyszyn Bob.Stasyszyn@securekey.com
closes #35
=> [#35] Add hooks for pvt r/w set filtering

core/committer/committer_impl.go, core/peer/peer.go, extensions/collections/retriever/retriever.go, extensions/collections/retriever/retriever_test.go, extensions/gossip/api/gossipapi.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/blockpublisher/blockpublisher_test.go, extensions/gossip/dispatcher/dispatcher.go, extensions/gossip/dispatcher/dispatcher_test.go, extensions/gossip/mocks/blockpublisher.go, gossip/service/gossip_service.go, gossip/service/gossip_service_test.go, gossip/service/integration_test.go, peer/node/start.go
=> [#36] Add hooks for block publisher

images/orderer/Dockerfile, images/peer/Dockerfile
=> [#44] Building peer image with multiple GO_TAGS is failing

core/ledger/kvledger/kv_ledger_provider_test.go, core/ledger/kvledger/pkg_test.go
=> [#42] Fix TestLedgerBackup unit test

core/config/configtest/config.go
=> sampleconfig location is hardcoded

core/ledger/kvledger/txmgmt/privacyenabledstate/common_storage_db.go, extensions/statedb/store.go, extensions/statedb/store_test.go
=> [#50] Hook for State DB Caching

README.md
Update Contribution and Licence details in README to be in sync with other TrustBloc projects.
Closes #61 
=> docs: Update Contribution and Licence details in README

core/peer/peer.go, extensions/go.mod, extensions/go.sum, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, extensions/roles/ledger_roles_config.go, gossip/service/gossip_service.go, gossip/state/metrics_test.go, gossip/state/state.go, gossip/state/state_test.go
=> feat: role based features in gossip state provider

cmd/peer/main_test.go, core/ledger/kvledger/hashcheck_pvtdata_test.go, core/ledger/kvledger/kv_ledger_provider.go, core/ledger/kvledger/kv_ledger_provider_test.go, core/ledger/kvledger/tests/env.go, core/ledger/ledgermgmt/ledger_mgmt_test.go, core/ledger/ledgermgmt/ledger_mgmt_test_exports.go, core/ledger/ledgerstorage/store.go, core/ledger/ledgerstorage/store_test.go, core/peer/peer_test.go, extensions/blkstorage/store.go, extensions/blkstorage/store_test.go, extensions/idstore/store.go, extensions/idstore/store_test.go, extensions/pvtdatastorage/store.go, extensions/pvtdatastorage/store_test.go, extensions/testutil/ext_test_env.go
=> feat: Pass Ledger Config details to Extensions

core/peer/peer.go, extensions/gossip/api/gossipapi.go, extensions/gossip/state/state.go
- passing channel ID to few handler functions
-related to #65
=> refactor: block publisher handlers to use channelID

extensions/gossip/api/gossipapi.go
=> feat: Add txIndex for BlockPublisher handlers

extensions/gossip/service/service.go, extensions/gossip/service/service_test.go, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, gossip/service/gossip_service.go, gossip/state/state.go
- added new handle extension which can be used to extend private data
reconciler flag
- using blocking mode in gossip state extensions
related to #96
=> feat: pvtdata reconciller handle for role based features

gossip/privdata/pull.go
When private data is requested (pulled) from another peer, a response is
expected for every key that it requests or it times out after 5s. The
remote peer handles the request for each key by checking if it has the
data locally and if the requesting peer has access to the collection for
the key. If this criteria is not met then it does not produce a response
for that key and ends up replying with an empty array of private data.
This leaves the requesting peer waiting 5s before timing out.
This patch changes the behavior slightly in that the remote peer
responds to the request with an empty payload if it cannot fulfill the
request, so that the requesting peer knows immediately that the peer
does not have the data.
closes #116
=> perf: Performance improvement for pulling private data

core/endorser/endorser.go, core/peer/peer.go, extensions/collections/api/support/support.go, extensions/collections/retriever/retriever.go, extensions/collections/retriever/retriever_test.go, extensions/collections/storeprovider/storeprovider.go, extensions/endorser/endorser.go, extensions/endorser/endorser_test.go, extensions/gossip/dispatcher/dispatcher.go, extensions/gossip/dispatcher/dispatcher_test.go, gossip/service/gossip_service.go, internal/peer/node/start.go
All external resources are declared but not initialized. Initialization of the resources will be performed if they are registered with the resource manager.
closes #129
=> refactor: Refactor resources in preparation for dependency injection

common/util/retry/retry.go
Increase retry attempts from 5 to 10.
closes #131
=> chore: Increase retry attempts for couch DB

core/peer/peer.go, extensions/chaincode/api/cceventmgr.go, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, internal/peer/node/providers.go, internal/peer/node/start.go
=> feat: Convert block publisher to a resource

ci/azp-dependencies-mod.yml, ci/azure-pipelines-mod.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> ci: add azp for mod

ci/azure-pipelines-mod.yml
=> chore: Added unit-test and integration-test jobs to Azure

core/ledger/kvledger/benchmark/chainmgmt/sanity_test.go
=> fix: Set up extension test env for unit tests

core/ledger/util/couchdb/couchdb.go, core/ledger/util/couchdb/couchdbutil.go, core/ledger/util/couchdb/couchdbutil_ext.go, core/ledger/util/couchdb/couchdbutil_ext_test.go, extensions/storage/dbname/resolver.go, extensions/storage/dbname/resolver_test.go
=> feat: Added hook to allow extensions to change CouchDB name

internal/peer/node/start.go
=> chore: Added ACL provider and endorser.Support as resources

core/peer/peer.go, core/peer/peer_test.go, internal/peer/node/start.go
=> fix: Reverted change that removed peer InitializeChannel

core/chaincode/chaincode_support_test.go
=> fix: Set up couch DB test env for unit test

cmd/peer/main_test.go, core/config/configtest/config.go, core/ledger/kvledger/kv_ledger_provider.go, core/ledger/kvledger/kv_ledger_provider_test.go, core/ledger/kvledger/kv_ledger_test.go, core/ledger/kvledger/pause_resume.go, core/ledger/kvledger/pause_resume_test.go, core/ledger/kvledger/snapshot_test.go, core/ledger/kvledger/tests/env.go, core/ledger/kvledger/tests/v1x_test.go, core/ledger/kvledger/upgrade_dbs_test.go, extensions/storage/api/api.go, extensions/storage/idstore/mock_idstore.go, gossip/service/gossip_service_test.go, internal/peer/node/pause.go, internal/peer/node/pause_test.go, internal/peer/node/rebuild_dbs_test.go, internal/peer/node/resume.go, internal/peer/node/resume_test.go
=> fix: Fix fabric-peer-ext unit tests

core/ledger/kvledger/kv_ledger.go, extensions/gossip/api/gossipapi.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/blockpublisher/blockpublisher_test.go, extensions/gossip/mocks/blockpublisher.go, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, gossip/privdata/coordinator.go, gossip/privdata/coordinator_test.go, gossip/state/state.go, gossip/state/state_test.go
Modified the BlockPublisher API to also publish private data.
closes #217
=> feat: Publish private data with BlockPublisher

peer/node/common.go, peer/node/common_test.go, peer/node/main.go, peer/node/main_test.go
=> fix: bring back peer/node pkg

core/ledger/kvledger/kv_ledger_provider.go, core/ledger/kvledger/tests/v1x_test.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext_test.go
=> fix: Invalidate state cache on non-committing peers after write

internal/peer/node/rollback_test.go
=> fix: skip rollback test

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext.go, extensions/gossip/api/gossipapi.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/blockpublisher/blockpublisher_test.go, extensions/gossip/mocks/blockpublisher.go
=> fix: Delete collection hash entries from cache on update

core/ledger/kvledger/tests/missing_pvtdata_retrieval_test.go, core/ledger/kvledger/tests/reset_test.go, core/ledger/kvledger/tests/rollback_test.go, extensions/ledger/kvledger/reset.go, internal/peer/node/rollback.go
=> feat: Enable TestRollbackKVLedger

core/ledger/kvledger/tests/missing_pvtdata_retrieval_test.go
=> chore: enable TestGetMissingPvtDataAfterRollback

core/ledger/kvledger/tests/rollback_test.go
=> chore: enable TestRollbackKVLedgerWithBTL

internal/peer/node/rollback.go, internal/peer/node/rollback_test.go
=> chore: Enable TestRollbackCmd

core/ledger/kvledger/tests/v1x_test.go, core/ledger/kvledger/tests/v20_test.go, extensions/ledger/kvledger/rebuild_dbs.go, internal/peer/node/rebuild_dbs.go
=> feat: add hook for RebuildDBs

core/ledger/kvledger/tests/v1x_test.go, extensions/ledger/kvledger/upgrade_dbs.go, internal/peer/node/rebuild_dbs_test.go, internal/peer/node/upgrade_dbs.go
=> feat: add hook for UpgradeDBs

core/ledger/kvledger/rebuild_dbs_test.go, core/ledger/kvledger/upgrade_dbs_test.go, internal/peer/node/rebuild_dbs_test.go, internal/peer/node/upgrade_dbs_test.go
=> chore: Add comment for skipped unit test

core/ledger/kvledger/pause_resume_test.go, extensions/ledger/kvledger/pause_resume.go, internal/peer/node/pause.go, internal/peer/node/resume.go
=> feat: add hook for PauseAndResume ledger

internal/peer/node/pause_test.go, internal/peer/node/resume_test.go
=> fix: Enable PauseAndResume unit tests

core/ledger/kvledger/pause_resume_test.go
=> chore: add skip for TestPauseAndResume and TestPauseAndResumeErrors

core/ledger/kvledger/tests/reset_test.go, extensions/ledger/kvledger/reset.go, internal/peer/node/reset.go, internal/peer/node/start.go
=> feat: Add hook for ResetAllKVLedgers and ClearPreResetHeight

core/ledger/kvledger/tests/reset_test.go, extensions/ledger/kvledger/reset.go
=> chore: add hook for ResetBlockStore

core/ledger/kvledger/tests/reset_test.go
=> chore: Enable reset ledger unit tests

internal/peer/node/reset_test.go
=> fix: TestResetCmd

core/chaincode/chaincode_support.go, core/chaincode/lifecycle/cache.go, core/chaincode/lifecycle/custodian.go, core/chaincode/lifecycle/event_broker.go, core/chaincode/lifecycle/mock/chaincode_launcher.go, core/ledger/cceventmgmt/lsccstate_listener.go, extensions/chaincode/ucc.go, internal/peer/node/start.go
=> feat: Add hooks for in-process chaincode lifecycle

core/chaincode/lifecycle/scc.go, extensions/chaincode/ucc.go, extensions/chaincode/ucc_test.go
=> fix: Add support for IMPLICIT-ORG member

core/chaincode/lifecycle/scc.go, extensions/collections/policy/validator.go
=> feat: Invoke extended collection config validator

core/ledger/cceventmgmt/lsccstate_listener.go
Even though an in-process user chaincode was instantiated using Fabric 2 chaincode lifecycle, we still need to call HandleChaincodeDeploy so that the CouchDB indexes are created. For regular chaincode this is done during install, but in-process user chaincode is never installed.
close #257
=> fix: Call HandleChaincodeDeploy for in-process user chaincodes

core/ledger/kvledger/tests/reset_test.go, core/ledger/kvledger/tests/rollback_test.go, extensions/testutil/ext_test_env.go, internal/peer/node/reset_test.go
=> chore: Hook to skip checks for level DB dirs in unit-test

core/ledger/kvledger/tests/missing_pvtdata_retrieval_test.go
=> chore: Re-enable unit test: TestGetMissingPvtData

core/endorser/endorser.go, extensions/config/config.go, extensions/config/config_test.go, extensions/go.sum, internal/peer/node/start.go
=> feat: Add config to skip checks for duplicate transactions on endorser

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext_test.go
=> fix: Fix panic in cache-updates unit test

ci/azure-pipelines-merge.yml, ci/azure-pipelines-mod.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: disable upstream pipeline

bccsp/pkcs11/ctxhandle.go, bccsp/pkcs11/pkcs11.go, bccsp/pkcs11/pkcs11_test.go
- Refer issue #293 for scenarios covered
- Closes #293
=> feat: PKCS11 resilience
