core/endorser/endorser.go, extensions/endorser/endorser.go, extensions/endorser/endorser_test.go
Add an extension point which allows for filtering of read-write
sets before they are endorsed and sent to the orderer.
closes #54 
=> feat: Filter read-write sets during endorsement

core/peer/peer.go
Change the function, CollectionDataStoreFactory(), to return an interface so that
it may be more easily overridden by extensions.
closes #57
=> chore: Update CollectionDataStoreFactory() to return interface

core/peer/peer.go
The collection store provider variable in peer.go should be using the
interface CollStoreProvider instead of the StoreProvider struct.
closes #59
=> fix: Use CollStoreProvider interface instead of struct

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_test_export.go, extensions/testutil/ext_test_env.go
The couchDB test clean up function 'casts' DBProvider to CouchDBProvider. This limits the ability to wrap this in other DBProviders. This new extension gets the couchDB wrapped in other VersionedDBProvider.
Closes #63
=> feat: Add hook to State CouchDB cleanup function

core/ledger/kvledger/custom_processor_test.go, core/ledger/kvledger/hashcheck_pvtdata_test.go, core/ledger/kvledger/kv_ledger_provider_test.go, core/ledger/kvledger/tests/rebuild_test.go, core/ledger/ledgermgmt/ledger_mgmt_test.go, core/ledger/ledgerstorage/store_test.go, internal/peer/node/start_test.go, peer/node/main_test.go
Add fabric-peer-ext CouchDB hooks which were purged during #70 (files were deleted in fabric which had the hooks).
Closes #74
=> chore: Add fabric-peer-ext CouchDB hooks

core/peer/peer.go, extensions/gossip/state/state.go
to handle chaincode deploy in block handler, the extension implement
might need channel ID.
related to #66
=> feat: passing channel ID in add block handler

core/ledger/util/couchdb/couchdb_ext_test.go
The original value of MaxRetries count was specifically set to 5 in CouchDBExt retry test cases https://github.com/trustbloc/fabric-mod/commit/dbf261c87eea5555d7c015bb843c2107f28f1b9c#diff-e4247e115c4f9b9eb3723c86acb39b70R153. The latest fabric has new design for CouchDB configuration and this change was lost during merge process.
=> test: CouchDB Ext UnitTest - Update MaxRetries count

extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, gossip/state/state.go
- removed interfaces and other features which aren't needed for typical
gossip state provider extension implementations.
related to #66
=> feat: cleanup gossip state extension

peer/node/common.go, peer/node/common_test.go
As part of HL fabric restructure, the peer code was moved inside internal folder and is not accessible from other modules. Bloc-node uses these functions to initialize the peer. Exposed the function and constant through new pacakage.
Implements #82
=> feat: Expose peer InitCmd function and CmdRoot const

docs/source/gobackextension.rst, docs/source/index.rst, extensions/docs/source/hyperledgerfabric.rst, extensions/docs/source/index.rst, readthedocs.yaml
- Readthedocs.yml customize the conf.py file path to extensions/docs/source
This will point fabric-mod to extension doc.
- Instead of cross referencing and host hyperledger documentation on trustblco
It makes more sense to hyperlink the supported version of hyperledger documentation.
Closes: #75
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>
=> docs: Fabric-mod Documentation broken link fix

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/peer/peer.go, core/scc/cscc/configure.go, extensions/peer/peer.go, extensions/peer/peer_test.go, extensions/storage/couchdb/couchdb.go, extensions/storage/couchdb/couchdb_test.go
- added extensions for CreateChainFromBlock in cscc join channel so that
it can be extended to provide role based features
- added create couch db extension which can be extended to provided role
based features
=> feat: extensions in cscc join channel and create couch db

core/peer/peer.go, core/scc/cscc/configure.go, extensions/channel/channel.go, extensions/channel/channel_test.go
- package name for `extensions/peer` changed to 'extensions/channel'
- RegisterChannelInitializer function signature changed
Reason: extension for above package in fabric-peer-ext will look like
'mod/peer/peer' if we go with old name. And, ChannelInitializer in extension
doesn't need handle to get current config block from ledger since it already has one.
related to #96
=> refactor: fixing package names

internal/peer/chaincode/common.go, internal/peer/chaincode/offledgercollconfig_test.go
Add support for DCAS and OFFLEDGER collection types in the JSON collection config used by the peer binary when instantiating a chain code.
closes #92
=> feat: Add support for off-ledger and DCAS in config parser

core/ledger/kvledger/kv_ledger.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/peer/peer.go, extensions/channel/channel.go, extensions/storage/recover/recoverdb.go, extensions/storage/recover/recoverdb_test.go
- need to pass peer.InitChain(cid) as a handle to avoid import cycle
issues in fabric-peer-ext
- fixing stutter in recover.RecoverDBHandle()
=> refactor: Init chain handle for channel initializer extensions

core/endorser/endorser.go, extensions/endorser/api/endorser.go, extensions/endorser/endorser.go, extensions/endorser/endorser_test.go
The collection config package that is assembled by the endorser removes
configs for collections in which there was no write set and therefore
the error 'config for collection [xxx] not found' results. This commit
removes the dependency on the collection config package and uses the
collection config retriever to manage collection configs.
closes #98
=> fix: Fix for collection config not found

extensions/chaincode/scc.go, extensions/chaincode/scc_test.go, internal/peer/node/gossipprovider.go, internal/peer/node/start.go
Added a hook to load all extended system chaincodes and register them along
with the built-in system chaincodes.
closes #67
Co-authored-by: Rolson Quadras <rolson.quadras@securekey.com>
=> feat: Load system chaincode from extension

core/committer/committer_impl.go, core/deliverservice/blocksprovider/blocksprovider.go, core/peer/peer.go, extensions/channel/channel.go, extensions/gossip/api/gossipapi.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/mocks/blockpublisher.go, extensions/gossip/service/service.go, extensions/gossip/service/service_test.go, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go, gossip/service/gossip_service.go, gossip/state/state.go, gossip/state/state_test.go
- role based extension in anti entropy while request new blocks
- role based extension for ledger height calculations
- ChannelInitializer extension to use current config block
- role based extension for gossip in deliveryservice  blocks provider
- block publisher to provide ledger height info
related to #96
=> feat: gossip extensions to support role based features

common/ledger/blkstorage/blockstorage.go, common/ledger/blkstorage/fsblkstorage/fs_blockstore.go, common/ledger/blockledger/file/impl_test.go, core/chaincode/mock/peer_ledger.go, core/committer/committer_test.go, core/committer/txvalidator/v14/validator_test.go, core/ledger/kvledger/kv_ledger.go, core/ledger/ledger_interface.go, core/ledger/ledgerstorage/store.go, extensions/ledger/api/ledgerapi.go, extensions/ledger/kvledger.go, extensions/ledger/kvledger_test.go, extensions/storage/blkstorage/api/blkstorageapi.go
- added extension to existing block store interface to add check point
block features which can be used to maintain local checkpoint info on
current block status of the store.
- also added corresponding extensions in PeerLedger so that it can be
used to update checkpoint info in underlying blockstore.
-fsb block store implementation doesn't support blockstore checkpoints
-related to #108
=> feat: Checkpoint block implementation in block store

core/endorser/endorser.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/ccupgradehandler.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/ccupgradehandler_test.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/peer/peer.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/blockpublisher/blockpublisher_test.go, extensions/storage/statedb/statedb.go, internal/peer/node/start.go
- clearing lscc state cache for given chaincode in statecouchdb after CC
upgrade
related to #96
=> feat: lscc state cache clear on CC upgrade

extensions/gossip/api/gossipapi.go, extensions/gossip/blockpublisher/blockpublisher.go, extensions/gossip/blockpublisher/blockpublisher_test.go, extensions/gossip/mocks/blockpublisher.go
Added the function, AddLSCCWriteHandler, to BlockPublisher so that clients can register for chaincode instantiation and upgrade events. The handler is provided the chaincode data and collection config package.
closes #112
=> feat: Add LSCC write events to BlockPublisher

core/peer/peer.go, extensions/gossip/state/state.go, extensions/gossip/state/state_test.go
Renamed AddBlockHandler to ChannelJoined since it's invoked when the peer joins the channel. Also added the channel ID and ledger to the function signature.
closes #113
=> chore: Rename AddBlockHandler

internal/peer/node/start.go
Resources are now initialized before the channels are initialized, otherwise a panic occurs on peer restart.
closes #133
=> fix: Initialize resources before channels

extensions/gossip/api/gossipapi.go, internal/peer/node/providers.go, internal/peer/node/start.go
Resources are initialized before external system chaincodes so that a system chaincode can be injected with dependent resources.
Because of this change, the Gossip resource was also changed to a Gossip provider in order to defer the retrieval of the service (since the resource is initialized before Gossip).
closes # 135
=> feat: Initialize resources before system chaincodes

gossip/service/gossip_service_test.go
The unit test, TestWithStaticDeliverClientLeader, needs to be set up with the proper resources otherwise a panic results when running the unit tests is fabric-peer-ext.
closes #137
=> fix: Fix unit test TestWithStaticDeliverClientLeader in fabric-peer-ext

cmd/peer/main_test.go, cmd/peer/test_init.go, extensions/testutil/ext_test_env.go, gossip/service/gossip_service_test.go
Add an init() that is invoked only if build tag 'testing' is set and build the command with this tag. The init() func initializes all resource providers.
closes #139
=> fix: Fix for TestPluginLoadingFailure

scripts/run-unit-tests.sh
Doubled the unit-test timeout to 40m so that fabric-peer-ext unit tests don't time out.
closes #150
=> chore: Increased unit-test timeout

core/ledger/kvledger/kv_ledger_provider.go
On peer startup, the committer sets the 'under construction' flag while initializing the DB. A non-committing peer would detect the 'under construction' flag and attempt recovery. This results in a panic.
This fix disables recovery for non-committing peers.
closes #152
=> fix: Don't perform recovery if not committer

ci/azure-pipelines-mod.yml, core/chaincode/lifecycle/deployedcc_infoprovider.go, core/chaincode/lifecycle/deployedcc_infoprovider_test.go
Check for nil from legacy chaincode info provider and return an empty ChaincodeInfo struct, otherwise a panic results.
closes #156
=> fix: Panic when retrieving collection config for non-existent chaincode

core/cclifecycle/subscription.go, extensions/chaincode/ucc.go, internal/peer/node/start.go
After a restart, legacy chaincodes were not being registered since the chaincode directory path was not set. Also, in-process chaincodes were not being registered.
This patch sets the legacy chaincode path and adds all in-process chaincodes to the CC meta data.
closes #161
=> fix: Register legacy and in-process changecodes on startup

core/ledger/kvledger/txmgmt/privacyenabledstate/common_storage_db.go
If the peer does not have the 'committer' role then DB indexes should not be created for chaincode.
closes #163
=> fix: Don't add DB indexes if peer is not a committer

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/ledger/util/couchdb/couchdb.go, extensions/storage/dbname/resolver.go, extensions/storage/dbname/resolver_test.go
Multiple problems were fixed when checking for DB data version:
- A race condition exists in clustered mode when checking/writing the data version to the DB. Only a committer should be writing the data version.
- When using DB partitions, ensure that the DB name is encoded properly before adding to the ignore list.
- Do not examine databases that are not relevant to the peer (in the case of a shared database).
closes #175
=> fix: Panic when checking DB data version

extensions/go.mod, extensions/go.sum, go.mod, go.sum
Point to fabric-protos-go-ext v0.1.2.
closes #177
=> chore: Release 0.1.2

core/ledger/cceventmgmt/mgr.go, extensions/chaincode/api/api.go, extensions/chaincode/mock/usercc.gen.go
The signature of function, GetDBArtifacts, was changed such that the names of the collections for the chaincode are passed in as an argument. The in-process user chaincode decides which indexes should be returned for each collection. This allows for the names of the collections and the number of collections to be dynamic.
closes #179
=> feat: Get DB artifacts for specified collections

gossip/state/state.go
The extension function, AddPayload, should be called so that it can apply custom logic when adding a block (payload).
closes #181
=> fix: Call extension AddPayload when receiving a block from Gossip

core/handlers/library/extensions.go, core/handlers/library/extensions_test.go, core/handlers/library/registry.go, extensions/handlers/handlers.go, extensions/handlers/handlers_test.go, internal/peer/node/start.go
Added hooks to allow extensions to load Auth filters and Decorators using an alternative mechanism (other than Go plugins).
The handler registry was changed to perform lazy loading of handlers since the auth handlers were being loaded before the auth handler extensions were registered.
closes #185
=> feat: Hooks for loading Auth Filters and Decorators

internal/peer/node/start.go
Added external system chaincodes to the list of built-in system chaincodes so that they aren't prevented from being invoked.
closes #189
=> fix: Add external SCCs to built-in SCC list

internal/peer/node/start.go
=> chore: Register lifecycle.ValidatorCommitter as a resource

internal/peer/node/start.go
Register the lifecycle chaincode cache as a resource so that extensions may have access to it.
closes #244
=> feat: Register chaincode cache as a resource

core/ledger/kvledger/txmgmt/privacyenabledstate/db.go, core/ledger/kvledger/txmgmt/statedb/statedb.go
This code was left out in the Fabric 2.2 merge.
closes #248
=> fix: CouchDB indexes not created for in-process user chaincode

core/chaincode/chaincode_support.go, core/chaincode/lifecycle/cache.go, core/chaincode/lifecycle/custodian.go, core/chaincode/lifecycle/event_broker.go, extensions/chaincode/ucc.go, extensions/chaincode/ucc_test.go, internal/peer/node/start.go
For legacy chaincode, the ID of the chaincode was also including a minor version. This fix strips the minor version of the ID and uses this ID when registering handlers.
closes #251
=> fix: Strip minor version from ID when launching in-process user chaincode

core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext.go, core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb_ext_test.go
When the cache is accessed for private data, ensure that the version of the hashed key matches the cached version. If it doesn't match then the private data must be refreshed from the database, otherwise it errors out with the following:
- private data matching public hash version is not available. Public hash version = {BlockNum: 101, TxNum: 1}, Private data version = {BlockNum: 94, TxNum: 0}
closes #263
=> fix: Ensure private data version matches hashed version in cache

core/ledger/kvledger/tests/missing_pvtdata_retrieval_test.go
Skipping test 'TestGetMissingPvtData' for extensions since fabric-peer-ext does not currently support this feature for CouchDB.
closes #270
=> chore: Skip test 'TestGetMissingPvtData'

core/ledger/kvledger/tests/reset_test.go
require.Equal cannot reliably compare two protobufs. This change uses proto.Equal instead.
closes #276
=> fix: Use proto.Equal in unit test to compare two blocks

extensions/go.mod, extensions/go.sum, go.mod, go.sum
Update to fabric-protos-go-ext v0.1.5.
closes #286
=> chore: Release v0.1.5

core/ledger/kvledger/kv_ledger.go, core/ledger/kvledger/kv_ledger_provider.go, core/ledger/kvledger/txmgmt/txmgr/lockbased_txmgr.go, extensions/storage/statedb/statedb.go, integration/helpers/images.go
When a channel is created then, along with registering a state database, a query executor provider is also registered. The query executor provider returns query executors with and without a ledger lock. In some cases (such as with off-ledger and transient data) a ledger lock is not required and this will improve performance when reading data.
closes #291
=> feat: Register a query executor provider along with state DB
